name: endoscopy_tool
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  screenshot: ^3.0.0
  path_provider: ^2.1.5
  http: ^1.4.0
  media_kit: ^1.2.0
  media_kit_video: ^1.3.0
  media_kit_libs_macos_video: ^1.1.4
  media_kit_libs_windows_video: ^1.0.11
  window_size: ^0.1.0
  file_picker: ^10.2.0
  image_picker: ^1.1.2
  camera: ^0.11.1
  ffmpeg_kit_flutter_new: ^2.0.0


  cupertino_icons: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 400
